<?php
return array (
  3 => 
  array (
    'id' => '3',
    'catid' => '12',
    'typeid' => '0',
    'title' => '西方管乐艺术论稿',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2015/0712/20150712102709926.jpg',
    'keywords' => '艺术论 管乐',
    'description' => '西方管乐艺术论稿',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=12&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436667900',
    'updatetime' => '1436669762',
    'hitsid' => 'c-12-3',
    'views' => '3',
    'yesterdayviews' => '0',
    'dayviews' => '3',
    'weekviews' => '3',
    'monthviews' => '3',
  ),
  1 => 
  array (
    'id' => '1',
    'catid' => '12',
    'typeid' => '0',
    'title' => '西方管乐艺术史',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2015/0712/20150712102307585.jpg',
    'keywords' => '管乐 艺术史',
    'description' => '书是国内第一部介绍西方管乐音乐发展和艺术成就的专著，也是在研究西方器乐音乐方面为数不多的专史性著作。作者将管乐实践经验和理论功底相',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=12&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436667772',
    'updatetime' => '1436669766',
    'hitsid' => 'c-12-1',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '12',
    'typeid' => '0',
    'title' => '西方管乐合奏曲精选·初级3',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2015/0712/20150712102452338.jpg',
    'keywords' => '管乐',
    'description' => '西方管乐合奏曲精选&middot;初级3',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=12&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436667834',
    'updatetime' => '1436667899',
    'hitsid' => 'c-12-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>