<?php
return array (
  7 => 
  array (
    'id' => '7',
    'catid' => '14',
    'typeid' => '0',
    'title' => '李天池博士管乐教育系列讲座开始报名',
    'style' => '',
    'thumb' => '',
    'keywords' => '天池 管乐 讲座',
    'description' => '管乐团启蒙教育 &mdash;&mdash; 从零到第一场音乐会     From Zero to the First Concert讲师：李天池博士  新加坡管乐协会主席      ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=14&id=7',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436666866',
    'updatetime' => '1436869566',
    'hitsid' => 'c-1-7',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '2',
    'weekviews' => '2',
    'monthviews' => '2',
  ),
  3 => 
  array (
    'id' => '3',
    'catid' => '14',
    'typeid' => '0',
    'title' => '著名美国低音长号演奏家本杰明•格林赴深圳',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '2015年深圳大剧院爱乐乐团普及音乐会自开始以来，深受市民朋友欢迎。在5月15日（本周五），第十一届中国（深圳）文博会艺术节，深圳大剧院   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=14&id=3',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436666433',
    'updatetime' => '1436666450',
    'hitsid' => 'c-1-3',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  4 => 
  array (
    'id' => '4',
    'catid' => '14',
    'typeid' => '0',
    'title' => '关于举办“2015深港管乐艺术节  暨第五届深圳管乐打击乐比',
    'style' => '',
    'thumb' => '',
    'keywords' => '管乐 深港 艺术节',
    'description' => '深圳，是青春时尚绿色之都，是多元文化交融荟萃之地。在这里，时代的气息、生命的多彩闪烁得更加淋漓尽致；传统的文化与国际的潮流，共同交   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=14&id=4',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436666452',
    'updatetime' => '1436666793',
    'hitsid' => 'c-1-4',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  5 => 
  array (
    'id' => '5',
    'catid' => '14',
    'typeid' => '0',
    'title' => '著名指挥家林友声教授应邀莅临我省指导讲学',
    'style' => '',
    'thumb' => '',
    'keywords' => '指挥家 教授 林友声',
    'description' => ' 应广东省管乐协会邀请，著名指挥家林友声教授将于2015年4月11日-14日莅临我省，对广东省管乐协会选派参加5月1日在上海举行的中华杯中国第   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=14&id=5',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436666806',
    'updatetime' => '1436666834',
    'hitsid' => 'c-1-5',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  6 => 
  array (
    'id' => '6',
    'catid' => '14',
    'typeid' => '0',
    'title' => '深圳市管乐协会单簧管萨克斯管专业委员会成立',
    'style' => '',
    'thumb' => 'http://localhost/phpcms/uploadfile/2015/0712/20150712100737657.jpg',
    'keywords' => '萨克斯管 单簧管 管乐',
    'description' => '2015年3月26日深圳市管乐协会单簧管萨克斯管专业委员会代表大会顺利召开，与会的来宾有深圳市文体旅游局艺术处处长、深圳市音乐家协会副主   ',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=14&id=6',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436666835',
    'updatetime' => '1436666857',
    'hitsid' => 'c-1-6',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  8 => 
  array (
    'id' => '8',
    'catid' => '14',
    'typeid' => '0',
    'title' => '深圳龙华中心小学雏鹰行进打击乐团  参加“2015台湾国际行',
    'style' => '',
    'thumb' => '',
    'keywords' => '打击乐团 龙华 雏鹰',
    'description' => '深圳龙华中心小学雏鹰行进打击乐团，于2015年5月3日参加由台湾行进乐联盟在彰化举办的2015台湾国际行进乐队比赛，获得小学组第一名及国际行   ',
    'posids' => '1',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=14&id=8',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436666888',
    'updatetime' => '1436666919',
    'hitsid' => 'c-1-8',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>