<?php
return array (
  11 => 
  array (
    'id' => '11',
    'catid' => '15',
    'typeid' => '0',
    'title' => '某某某乐队2的历史',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '某某某乐队2的历史',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=15&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436860941',
    'updatetime' => '1436861208',
    'hitsid' => 'c-1-11',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  10 => 
  array (
    'id' => '10',
    'catid' => '15',
    'typeid' => '0',
    'title' => '某某某乐队',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '某某某乐队',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=15&id=10',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436860887',
    'updatetime' => '1436860931',
    'hitsid' => 'c-1-10',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>