<?php
return array (
  13 => 
  array (
    'id' => '13',
    'catid' => '16',
    'typeid' => '0',
    'title' => '重要活动2',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '重要活动2重要活动2重要活动2重要活动2',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=16&id=13',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436861081',
    'updatetime' => '1436869598',
    'hitsid' => 'c-1-13',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  12 => 
  array (
    'id' => '12',
    'catid' => '16',
    'typeid' => '0',
    'title' => '重要活动1',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '重要活动1重要活动1重要活动1重要活动1',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=16&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436860967',
    'updatetime' => '1436861080',
    'hitsid' => 'c-1-12',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  14 => 
  array (
    'id' => '14',
    'catid' => '16',
    'typeid' => '0',
    'title' => '重要活动3',
    'style' => '',
    'thumb' => '',
    'keywords' => '',
    'description' => '重要活动3重要活动3重要活动3重要活动3',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=16&id=14',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436861089',
    'updatetime' => '1436861094',
    'hitsid' => 'c-1-14',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>