<?php
return array (
  1 => 
  array (
    'id' => '1',
    'catid' => '9',
    'typeid' => '0',
    'title' => '某某某通知公告',
    'style' => '',
    'thumb' => '',
    'keywords' => '通知公告',
    'description' => '今天晚上有雨',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=9&id=1',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436537165',
    'updatetime' => '1436537233',
    'hitsid' => 'c-1-1',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  2 => 
  array (
    'id' => '2',
    'catid' => '9',
    'typeid' => '0',
    'title' => '今天下午两点音乐课',
    'style' => '',
    'thumb' => '',
    'keywords' => '音乐课',
    'description' => '上课时间为下午两点，老师：张老师请各位同学务必出席',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=9&id=2',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436537234',
    'updatetime' => '1436537286',
    'hitsid' => 'c-1-2',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  9 => 
  array (
    'id' => '9',
    'catid' => '9',
    'typeid' => '0',
    'title' => '测试公告2',
    'style' => '',
    'thumb' => '',
    'keywords' => '公告',
    'description' => '测试公告2测试公告2测试公告2测试公告2测试公告2',
    'posids' => '0',
    'url' => 'http://localhost/phpcms/index.php?m=content&c=index&a=show&catid=9&id=9',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1436670394',
    'updatetime' => '1436670414',
    'hitsid' => 'c-1-9',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>